### ISSUE TITLE
[Crash] ViewPropertyAnimator.java line 1111 - Tmp detached view should be removed from RecyclerView before it can be recycled

### ISSUE THREAD

**Issue by raghav2945** [lisawray/groupie#416]
**Describe the bug**
We are receiving a crash, which is becoming more frequent by the day. It generates a Fatal Exception, "java.lang.IllegalArgumentException." The complete error message that we are receiving is as follows:

**_"Tmp detached view should be removed from RecyclerView before it can be recycled: GroupieViewHolder{6fb6182 position=-1 id=-1, oldPos=-1, pLpos:-1 removed tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{9962bc5 VFED..... ......ID 0,150-480,451 #7f0a0530 app:id/recyclerView}, adapter:com.xwray.groupie.GroupAdapter@5a4d91a, layout:androidx.recyclerview.widget.GridLayoutManager@5728c4b, context:com.audiomack.ui.home.HomeActivity@17039d"_**

**Stack-trace**

```
Fatal Exception: java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: GroupieViewHolder{6fb6182 position=-1 id=-1, oldPos=-1, pLpos:-1 removed tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{9962bc5 VFED..... ......ID 0,150-480,451 #7f0a0530 app:id/recyclerView}, adapter:com.xwray.groupie.GroupAdapter@5a4d91a, layout:androidx.recyclerview.widget.GridLayoutManager@5728c4b, context:com.audiomack.ui.home.HomeActivity@17039d7
       at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6620)
       at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1525)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13109)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13611)
       at androidx.recyclerview.widget.SimpleItemAnimator.dispatchAddFinished(SimpleItemAnimator.java:302)
       at androidx.recyclerview.widget.DefaultItemAnimator$5.onAnimationEnd(DefaultItemAnimator.java:247)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1122)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.-wrap2()
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:509)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**To Reproduce**
We are unable to reproduce this issue locally, but it ranks in the top ten of our Firebase Crashlytics.

**Expected behavior**
We do not anticipate such a crash.

**Library version**
[2.10.0]

**Additional context**
We had a similar crash and solved it by removing the animation flag from the immediate recyclerview's parent.
Removed: android:animateLayoutChanges="true"

**Comment by raghav2945** [comment]
We need to reopen our issue, as it is not completely resolved. Will depend on your solution on it.

**Comment by raghav2945** [comment]
We should close this issue because the number of occurrences has decreased slightly and the count is rarely more than 1-2.
