### ISSUE TITLE
[ANR] com.xwray.groupie

### ISSUE THREAD

**Issue by raghav2945** [lisawray/groupie#417]
**Describe the bug**
We've been using your library for a while, but we've recently started getting ANRs from your component. For your convenience, I've included two examples of such ANRs. Please take a look at these issues and address them so that we receive less ANR from this wonderful library.

**Stack-trace**
1. com.xwray.groupie.GroupAdapter.onCreateViewHolder
```
main (native): tid=1 systid=5804
#00 pc 0x5e4a8 libc.so 
#01 pc 0x131bb3 libart.so 
#02 pc 0x4d409b libart.so 
#03 pc 0x4d3f21 libart.so 
       at android.content.res.AssetManager.nativeOpenXmlAsset(Native method)
       at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1144)
       at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1467)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2545)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2521)
       at android.content.res.Resources.getLayout(Resources.java:1362)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:530)
       at com.xwray.groupie.GroupAdapter.onCreateViewHolder(GroupAdapter.java:221)
       at com.xwray.groupie.GroupAdapter.onCreateViewHolder(GroupAdapter.java:20)
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
       at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
       at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
       at android.view.View.measure(View.java:27131)
       at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:792)
       at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:480)
       at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:134)
       at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:277)
       at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:119)
       at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1578)
       at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1690)
       at android.view.View.measure(View.java:27131)
       at androidx.recyclerview.widget.GridLayoutManager.measureChildWithDecorationsAndMargin(GridLayoutManager.java:775)
       at androidx.recyclerview.widget.GridLayoutManager.measureChild(GridLayoutManager.java:746)
       at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:607)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
       at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
2. com.xwray.groupie.Item.
```
main (runnable): tid=1 systid=21850
       at sun.misc.Unsafe.getAndAddLong(Unsafe.java:480)
       at java.util.concurrent.atomic.AtomicLong.decrementAndGet(AtomicLong.java:212)
       at com.xwray.groupie.Item.<init>(Item.java:23)
       at com.xwray.groupie.viewbinding.BindableItem.<init>(BindableItem.java:26)
       at com.audiomack.utils.groupie.TitleHeaderItem.<init>(TitleHeaderItem.kt:18)
       at com.audiomack.utils.groupie.TitleHeaderItem.<init>(TitleHeaderItem.kt:12)
       at com.audiomack.ui.discover.DiscoverFragment.worldArticlesObserver$lambda-36(DiscoverFragment.kt:422)
       at com.audiomack.ui.discover.DiscoverFragment.lambda$JDnGbECSkCyq9sOn-H8NlIlfWMQ(DiscoverFragment.kt:18446744073709552000)
       at com.audiomack.ui.discover.-$$Lambda$DiscoverFragment$JDnGbECSkCyq9sOn-H8NlIlfWMQ.onChanged(lambda:18446744073709552000)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
       at com.audiomack.ui.discover.DiscoverViewModel.loadMoreWorldPosts$lambda-22(DiscoverViewModel.kt:450)
       at com.audiomack.ui.discover.DiscoverViewModel.lambda$oJAQIQKlIPyY0u3CJ45X0yeKm_k(DiscoverViewModel.kt:18446744073709552000)
       at com.audiomack.ui.discover.-$$Lambda$DiscoverViewModel$oJAQIQKlIPyY0u3CJ45X0yeKm_k.accept(lambda:18446744073709552000)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**To Reproduce**
Use our application in any low end devices

**Expected behavior**
We do not anticipate such a crash.

**Library version**
[2.10.0]

**Additional context**
NA

**Comment by raghav2945** [comment]
Since there's a tiny amount of occurrences wrt the top ANRS we can reasonably close this for time being.
