### ISSUE TITLE
[Crash] Crashes have occurred as a result of the use of groupie

### ISSUE THREAD

**Issue by raghav2945** [lisawray/groupie#420]
**Describe the bug**
During the getItem call, we ([Audiomack](https://audiomack.com/)) received two different crashes from your GroupUtils class. The first is an IndexOutOfBoundsException, while the second is a ConcurrentModificationException.

**Stack-trace :** IndexOutOfBoundsException
```
Caused by java.lang.IndexOutOfBoundsException: Wanted item at 21 but there are only 20 items
       at com.xwray.groupie.GroupUtils.getItem(GroupUtils.java:20)
       at com.xwray.groupie.DiffCallback.areItemsTheSame(DiffCallback.java:34)
       at androidx.recyclerview.widget.DiffUtil.backward(DiffUtil.java:300)
       at androidx.recyclerview.widget.DiffUtil.midPoint(DiffUtil.java:202)
       at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:146)
       at com.xwray.groupie.DiffTask.doInBackground$6f498465(DiffTask.java:44)
       at com.xwray.groupie.DiffTask.doInBackground(DiffTask.java:18)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
``` 
**Stack-trace :** ConcurrentModificationException
```
Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.xwray.groupie.GroupUtils.getItem(GroupUtils.java:12)
       at com.xwray.groupie.DiffCallback.areItemsTheSame(DiffCallback.java:34)
       at androidx.recyclerview.widget.DiffUtil.backward(DiffUtil.java:300)
       at androidx.recyclerview.widget.DiffUtil.midPoint(DiffUtil.java:202)
       at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:146)
       at com.xwray.groupie.DiffTask.doInBackground$6f498465(DiffTask.java:44)
       at com.xwray.groupie.DiffTask.doInBackground(DiffTask.java:18)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**To Reproduce**
Not known because the problem is not locally reproducible. This crash is being reported to us via Firebase.

**Expected behavior**
No crash expected.

**Library version**
2.10.0

**Comment by raghav2945** [comment]
I am closing this issue since there has been no update since the beginning. I was hoping for a response from the Groupie team.

**Comment by raghav2945** [comment]
@Zhuinden, Do you have something to say about this? If yes, please express your thoughts; otherwise, we wish to put this issue on hold/closer for the time being.

**Comment by raghav2945** [comment]
No response. Closing this again as I had opened it and now I don't have something to discuss anymore with respect to this issue.

**Comment by Zhuinden** [comment]
Technically it sounds like a pretty severe threading issue, which is why I reopened it, although I do wonder if you're using `updateAsync()`.

**Comment by raghav2945** [comment]
Okay, I get it. 
Yes, we do use a lot of times `updateAsync` with the groupie `GroupAdapter`. Is there a known issue with its use related to synchronization?

**Comment by msimonides** [comment]
I had a quick look at this and expanding/collapsing a group changes the total number of items (also as seen by the diff util). See `ExpandableGroup.getGroupCount()` that is used by `NestedGroup.getItemCount()`. `updateAsync` is working on a shallow copy of the groups so no wonder it crashes or produces incorrect results while expand/collaps happens during processing.

I'm not sure if there's an easy fix. My guess is that the diff task should probably be made aware of all items as if groups were all expanded and then somehow map the results back to the current expanded/collapsed state of each group. Might not be a trivial thing to do.

As a workaround in our apps we could block expanding/collapsing while the updateAsync is running ;)
